In [2]:
import pandas as pd

In [3]:


data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df = pd.DataFrame(data)

print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [4]:
lst = [['Alice', 25], ['Bob', 30]]
df = pd.DataFrame(lst, columns=['Name', 'Age'])

print(df)

    Name  Age
0  Alice   25
1    Bob   30

In [5]:
df.head()

    Name  Age
0  Alice   25
1    Bob   30

In [6]:
df.tail()

    Name  Age
0  Alice   25
1    Bob   30

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      object
 1   Age     2 non-null      int64
dtypes: int64(1), object(1)
memory usage: 160.0+ bytes

In [8]:
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [9]:
df['Name']

0    Alice
1      Bob
Name: Name, dtype: object

In [11]:
df[['Name', 'Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [14]:
df.loc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [13]:
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [15]:
df[df['Age'] > 25]

  Name  Age
1  Bob   30

In [16]:
df['Gender'] = ['F', 'M']

In [17]:
print(df)

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [ ]:
df.drop('Age', axis=1, inplace=True)

In [26]:
print(df)

    Name Gender
0  Alice      F
1    Bob      M

In [28]:
df.isnull()
df.dropna()
df.fillna(0)

    Name Gender
0  Alice      F
1    Bob      M

In [29]:


data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35],
        'Gender': ['F', 'M', 'M']}
df = pd.DataFrame(data)

print(df.groupby('Gender')['Age'].mean())

Gender
F    25.0
M    32.5
Name: Age, dtype: float64

In [30]:
df1 = pd.DataFrame({
    'key': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

df2 = pd.DataFrame({
    'key': [1, 2, 4],
    'Score': [85, 90, 95]
})

merged = pd.merge(df1, df2, on='key')
print(merged)

   key   Name  Score
0    1  Alice     85
1    2    Bob     90

In [31]:
df1 = pd.DataFrame({'Name': ['Alice', 'Bob']}, index=[0,1])
df2 = pd.DataFrame({'Score': [85, 90]}, index=[0,1])

joined = df1.join(df2)
print(joined)

    Name  Score
0  Alice     85
1    Bob     90

In [33]:
df.to_csv('data.csv', index=False)

In [35]:
df2 = pd.read_csv('data.csv')
print(df2)

      Name  Age Gender
0    Alice   25      F
1      Bob   30      M
2  Charlie   35      M

In [36]:
df.sort_values('Age')

      Name  Age Gender
0    Alice   25      F
1      Bob   30      M
2  Charlie   35      M

In [37]:
df['Age'].apply(lambda x: x + 1)

0    26
1    31
2    36
Name: Age, dtype: int64

In [38]:
df['Name'].unique()

array(['Alice', 'Bob', 'Charlie'], dtype=object)

In [39]:
df['Age'].value_counts()

Age
25    1
30    1
35    1
Name: count, dtype: int64